### ISSUE TITLE
Verify ie11 closest issue

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-c126#1]
Verify that the project is not affected by : 
https://github.com/geosolutions-it/MapStore2/issues/3147

If affected, fix the buildConfig properly

**Comment by Gnafu** [comment]
This is currently an issue and it is mitigated in production by:
- Adding the element-closest.js file in the dist folder
- Adding the following script tag to the index.html file head
```
<script src="dist/element-closest.js"></script>
```

I'm keeping this issue open because it should be properly fixed as it was done in https://github.com/geosolutions-it/MapStore2/commit/2f959b7ff5f72b90fa406cb08df5c047c9c20d3c
